services:
  app:
    build:
      context: .
    container_name: otel-app
    ports:
      - '8080:8080'
    environment:
      OTEL_METRICS_URL: http://grafana-lgtm:4318/v1/metrics
      OTEL_TRACES_ENDPOINT: http://grafana-lgtm:4318/v1/traces
      OTEL_LOGS_ENDPOINT: http://grafana-lgtm:4318/v1/logs
    depends_on:
      - grafana-lgtm

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    container_name: grafana-lgtm
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /otel-lgtm/grafana/conf/provisioning/dashboards/custom/logs-dashboard.json
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./dashboards/logs-dashboard.json:/otel-lgtm/grafana/conf/provisioning/dashboards/custom/logs-dashboard.json:ro
      - ./dashboards/dashboards-provisioning.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml:ro

  loadgen:
    image: grafana/k6:latest
    container_name: otel-loadgen
    profiles:
      - loadgen
    environment:
      BASE_URL: http://app:8080
    volumes:
      - ./scripts/traffic.js:/scripts/traffic.js:ro
    command: run /scripts/traffic.js
    depends_on:
      - app
