spring:
  application:
    name: otel

management:
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_URL:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTEL_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
  tracing:
    sampling:
      probability: 1.0

server:
  shutdown: immediate
logging:
  level:
    dev.trantor: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG
